[project]
name = "building-ai-applications-with-haystack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cohere-haystack>=7.0.0",
    "colorama>=0.4.6",
    "haystack-ai>=2.22.0",
    "ipykernel>=7.1.0",
    "python-dotenv>=1.2.1",
    "trafilatura>=2.0.0",
]
